controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
    
zenchron_file_manager:
    resource: "@ZenchronFileBundle/config/routes.php"
    prefix: / # Optional: The same prefix you use when importing the routes must be the "api_prefix" in the bundle options.
