# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    $criteriaValueResolver: 10
    api_prefix: '/api'
    
services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Domain/Entity'
            - '../src/Shared/{DependencyInjection,DQL,Contract,Common,Helper,Entity,Trait,Traits,Migrations,Tests}'
            - '../src/Shared/Infrastructure/DependencyInjection'
            - '../src/Shared/Presentation/Exception/ApiProblemLogErrorListener.php'
            - '../src/**/*Contract.php'
            - '../src/Shared/Domain'
            - '../src/Shared/Application/Contract'
            - '../src/Shared/Exception/'
            - '../src/Shared/Common'
            - '../src/Shared/Filter/Order/OrderBy.php'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
    App\Service\ThemeDiscoveryService:
        public: true
    
    App\EventSubscriber\CommandSubscriber:
        public: true
        tags:
            - { name: kernel.event_subscriber }
            
    App\Service\ThemeFilesystemService:
        public: true
        arguments:
            $filesystem: '@Symfony\Component\Filesystem\Filesystem'
            $projectDir: '%kernel.project_dir%'
            
    App\Service\ThemeRuntimeConfigurator:
        arguments:
            $twig: '@twig.loader.native_filesystem'
            $themeManager: '@App\Service\ThemeManager'
            $projectDir: '%kernel.project_dir%'
            
    App\Service\ComposerJsonVisualizer:
        public: true
        arguments:
            $projectDir: '%kernel.project_dir%'
            
    App\Controller\Admin\Theme\InstallAssetsController:
        arguments:
            $themeManager: '@App\Service\ThemeManager'
            $assetManager: '@App\Service\AssetManager'
            
    App\Service\ThemeManager:
        arguments:
            $themeRepository: '@App\Repository\ThemeRepository'
            $themeFilesystemService: '@App\Service\ThemeFilesystemService'
            
    App\Service\AssetManager:
        arguments:
            $projectDir: '%kernel.project_dir%'
            $filesystem: '@Symfony\Component\Filesystem\Filesystem'

    App\Command\ExportAssetsToThemeCommand:
        arguments:
            $assetManager: '@App\Service\AssetManager'
            $themeManager: '@App\Service\ThemeManager'
            
    App\Repository\ThemeRepository:
        arguments:
            $registry: '@Doctrine\Persistence\ManagerRegistry'
            
    App\EventSubscriber\ThemeConfiguratorSubscriber:
        arguments:
            $themeRuntimeConfigurator: '@App\Service\ThemeRuntimeConfigurator'
            
    _instanceof:
        App\Doctrine\AbstractEnumType:
            tags: [ 'app.doctrine_enum_type' ]
        
    App\FileManager\Presentation\Api\:
        resource: '../src/FileManager/Presentation/Api/*'
        tags: ['controller.service_arguments']
    App\FileManager\Presentation\BackOffice\:
        resource: '../src/FileManager/Presentation/BackOffice/*'
        tags: ['controller.service_arguments']

    App\Twig\PlaceholderImageExtension:
        arguments:
            $defaultImage: '/assets/1920x1080.svg'
        tags: ['twig.extension']

    # Shared Libraries 
    App\Shared\Domain\Event\InMemoryDomainEventPublisher: ~
    App\Shared\Domain\Event\DomainEventPublisherContract:
        alias: App\Shared\Domain\Event\InMemoryDomainEventPublisher
        
    App\Shared\Infrastructure\Site\SymfonySiteUrlResolver: ~
    App\Shared\Domain\Site\SiteUrlResolverContract:
        alias: App\Shared\Infrastructure\Site\SymfonySiteUrlResolver
        
    App\Shared\Filter\Attributes\CriteriaValueResolver:
        arguments:
            $paginationLimit: '$criteriaValueResolver'


    # File Manager
    App\FileManager\Infrastructure\Persistence\Orm\Repository\DoctrineOrmAvailableDatesMediaRepository: ~
    App\FileManager\Domain\Contract\AvailableDatesMediaRepositoryInterface:
        alias: App\FileManager\Infrastructure\Persistence\Orm\Repository\DoctrineOrmAvailableDatesMediaRepository
        
    App\FileManager\Infrastructure\Persistence\Orm\Repository\DoctrineOrmMimeMediaRepository: ~
    App\FileManager\Domain\Contract\MimeMediaRepositoryInterface:
        alias: App\FileManager\Infrastructure\Persistence\Orm\Repository\DoctrineOrmMimeMediaRepository
        
    App\FileManager\Infrastructure\Validation\UploadedFileValidator: ~
        
    App\FileManager\Infrastructure\Filesystem\Local\LocalFileRepository: ~
    App\FileManager\Domain\Contract\FileRepositoryInterface:
        alias: App\FileManager\Infrastructure\Filesystem\Local\LocalFileRepository
        
    App\FileManager\Domain\Contract\FilePathResolverInterface:
        alias: App\FileManager\Infrastructure\Filesystem\Local\LocalFilePathResolver
    
    App\FileManager\Domain\Contract\FileUrlResolverInterface:
        alias: App\FileManager\Infrastructure\Filesystem\Local\LocalFileUrlResolver
    App\FileManager\Infrastructure\Filesystem\Local\LocalFileUrlResolver: ~
    
    App\FileManager\Domain\Service\FileResizeHandler:
        arguments:
            $mediaResizes: !tagged_iterator media_bundle_extension.tag_media_resize
    
    App\FileManager\Infrastructure\FileManipulation\Thumbnails\Resize\ImagickGifFileResize: ~
    App\FileManager\Infrastructure\FileManipulation\Thumbnails\Resize\FfmpegGifFileResize: ~
    App\FileManager\Infrastructure\FileManipulation\Thumbnails\Resize\GifsicleGifFileResize: ~
    App\FileManager\Infrastructure\FileManipulation\Thumbnails\Resize\InterventionFileResize: ~
    
    App\FileManager\Domain\Service\GenerateThumbnailsHandler: ~
    
    App\FileManager\Application\FileManipulation\Thumbnails\GenerateThumbnails\AbstractGenerateImageThumbnails: ~
    App\FileManager\Application\FileManipulation\Thumbnails\GenerateThumbnails\GenerateImageThumbnails:
        parent: App\FileManager\Application\FileManipulation\Thumbnails\GenerateThumbnails\AbstractGenerateImageThumbnails
    
    App\FileManager\Application\FileManipulation\Thumbnails\GenerateThumbnails\GenerateGifImageThumbnails:
        parent: App\FileManager\Application\FileManipulation\Thumbnails\GenerateThumbnails\AbstractGenerateImageThumbnails
        
    App\FileManager\Domain\Service\FileCompressHandler:
        arguments:
            - !tagged_iterator
                tag: 'media_bundle_extension.tag_media_compress'
    
    App\FileManager\Infrastructure\FileManipulation\Compression\SpatieFileCompression: ~
    
